config/routes.rb
Rails.application.routes.draw do

  get 'contact_us' => "pages#contact", :as => "contact_us" 

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  root 'main#index'
  
  get "department" => "departments#show", :as => "department"
  
  resources :lectures_users
  resources :users
  resources :sessions
  resources :posts
  resources :lectures
  resources :departments
  resources :pages
  

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :lectures
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :department
  has_and_belongs_to_many :users
  has_many :posts
  self.per_page = 10
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :text
  validates_presence_of :price 
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }

  belongs_to :user
  belongs_to :lecture
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_presence_of :name
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /@ucsd\.edu/i 
  has_many :posts
  has_and_belongs_to_many :lectures

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def new
    @department = Department.new
  end
    
  def show
    @department = Department.find(params[:id])
    @lectures = @department.lectures.paginate(:page => params[:page])
  end

  def index
    @departments = Department.all
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def new
    @lecture = Lecture.new
  end

  def show
    @lecture = Lecture.find(params[:id])
    @posts = @lecture.posts
  end

  def index
    @lectures = Lecture.all
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def new
    @post = @Post.new
    @department = @Department.new
  end
  
  def index
    if current_user
      @lectures = current_user.lectures
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.lecture = Lecture.find(params.require(:post).fetch(:lecture))
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    if !current_user
      redirect_to root_url
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.user = current_user
    @post.lecture = Lecture.find(params.require(:post).fetch(:lecture))
    @post.update(post_params)
    if @post.save
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:text,:price)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
      @user = User.find(params[:id])
      @lectures = @user.lectures
      @posts = @user.posts
    if current_user
      @current_user = current_user
    else
      redirect_to root_url
    end
    
  end

  def create
    @user = User.new(user_params)
    @lectures = Lecture.where(:id => params[:lectures_chosen])
    @user.lectures << @lectures
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
    @user = current_user
  end
  
  def updateclasses
    @user = current_user
    @lectures = Lecture.where(:id => params[:lectures_chosen])
    @user.lectures.destroy_all
    @user.lectures << @lectures
    @user.save
    redirect_to current_user
  end

  def update
    @user = current_user
    @lectures = Lecture.where(:id => params[:lectures_chosen])
    @user.lectures.destroy_all
    @user.lectures << @lectures
    @user.update(user_params)
    if @user.save
      redirect_to @user
    else
      render 'edit'
    end
  end
    



  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/index.html.erb
<h1>Departments#index</h1>
<p>Find me in app/views/departments/index.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

<%= will_paginate @lectures %>

<% @lectures.each do |lecture| %>
  <%= lecture.name %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Tutor Database</title>
 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link href='http://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="top_nav navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Home and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topnavbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
      </button>
      <a class="pull-left"><%= link_to "Student Tutor Database", root_path, class: "title" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="topnavbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <!-- li class="dropdown"> 
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Departments <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
<li><a href="#">CSE</a></li>
            </ul>
          </li -->
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Log out", log_out_path %></li>
        <% else %>
          <li><%= link_to "Sign up", sign_up_path %></li>
          <li><%= link_to "Log in", log_in_path %><li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<%= yield %>

<nav class="bottom-nav navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bottomnavbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="bottomnavbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact Us", contact_us_path %></li>
      </ul>
    </div>
  </div>
</nav>



<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<br>
<br>



</body>
</html>

app/views/lectures/index.html.erb
<h1>Lectures#index</h1>
<p>Find me in app/views/lectures/index.html.erb</p>

app/views/lectures/show.html.erb
<h1 style="padding-top:10px"><%= @lecture.name %></h1>

<table>
  <tr>
    <th><u> Post </u></th>
    <th><u> User </u></th>
    <th><u> Price </u></th>
  </tr>
  <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post, class:"postlink" %>&nbsp&nbsp&nbsp&nbsp </td>
        <td><%= post.user.name %> &nbsp&nbsp&nbsp&nbsp </td>
        <td> $<%= post.price %>/hr</td>
      </tr>
  
  <% end %>
</table>

app/views/main/index.html.erb
<div class="container-fluid">
    <% if current_user %>

      <h2>Class Feed  
      <%= link_to "New Post", new_post_path, class: "btn btn-sm btn-default" %>
      </h2>
      <% if current_user.lectures.empty? %>
        Head over to your profile to add some classes! Click on the "Edit Profile" button to add classes and change your profile information.
      <% else %>
        <% @lectures.each do |lecture| %>
        <h3> <%= link_to lecture.name, lecture, class:"classlink" %> </h3>
        
          <table>
            <tr>
              <th><u> Post </u></th>
              <th><u> User </u></th>
              <th><u> Price </u></th>
            </tr>
            <% lecture.posts.each do |post| %>
              <tr class="postlist">
                  <td><%= link_to post.title, post %>&nbsp&nbsp&nbsp&nbsp</td>
                  <td><%= link_to post.user.name, post.user %>&nbsp&nbsp&nbsp&nbsp</td>
                  <td> $<%= post.price %>/hr</td>
              </tr>
            <% end %>
          </table>
        <% end %>
      <% end %> 
    <% else %>
     <div class="intro jumbotron">
      <h1>Get the right tutors, right now</h1>
      <h2>Find the help you need</h2>
      <h3>Make posts to get help</h3>
      <h3>Make posts to provide help</h3> <br>
      <%= link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-default" %>
    </div>
    <% end %>
  </div>

app/views/pages/contact.html.erb
<div class="container-fluid">
  <h2 style="text-align:center">For help, call us at either (805) 452-2283 (Dante Knowles) or (213) 254-7325 (Paul Kim) <br>
Or email us at dknowles@ucsd.edu for techincal support</h2>

  <!--FAQ accordian -->
  <div class="tab-content">
    <div class="tab-pan fad in active" id="faq">
      <div id="accordion" class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">How do I make a post?</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Click on "New post" on the home page.</p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">What if I can't find my class?</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Email us the class and we'll add it on right away!</p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">How do I add a class?</a>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Click on your username in the navigation bar, then click on "Edit Profile".</p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">How do I add more than one class?</a>
            </h4>
          </div>
          <div id="collapse4" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Click on your username in the navigation bar, then click on "Edit Profile". In the box listing all the the classes, choose your classes by clicking on one then hold your control button down while clicking on your other classes.</p>
            </div>
          </div>
        </div>



      </div>
    </div>
  </div>

</div>


</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post, url: {action: "update"} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :class %><br>
    <%= f.collection_select :lecture, Lecture.order(:name),:id,:name, include_blank: false %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :compensation %><br>
    <%= f.number_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', @post, class:"btn btn-sm btn-default" %>

app/views/posts/index.html.erb
<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Tutor Database</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<h1>New Post</h1>


<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @post.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :class %><br>
    <%= f.collection_select :lecture, Lecture.order(:name),:id,:name, include_blank: false %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

</body>
</html>

app/views/posts/show.html.erb
<div class="container-fluid">

<h2><%= @post.lecture.name %></h2><br>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @post.user.name, @post.user %>
  (<%= @post.user.email %>)
</p>
 
<p>
  <strong>Compensation:</strong>
  $<%= @post.price %>/hr
</p>

<p class="text">
  <strong>Text:</strong>
  <%= @post.text %>
</p><br>

<% if current_user.name == @post.user.name %>
  <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-sm btn-default" %>
  <%= link_to 'Delete', post_path(@post), class:"btn btn-sm btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</div>

app/views/users/edit.html.erb
        <%= form_for current_user, :action => :update do |f| %>
         <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>


  <p>Click on a class to add it to your class list. To choose multiple classes, hold down the control button while selecting the classes.</P>
         <%= select_tag "lectures_chosen", options_from_collection_for_select(Lecture.all, 'id', 'name', current_user.lectures.map{ |j| j.id }), :multiple => true %>
       <p class="button"> <%= f.submit %></p>
        <% end %>

app/views/users/new.html.erb
<% if not current_user %>
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
  <h1>
    <%= @user.name %>
    <% if @current_user.id == @user.id %>
      <%= link_to 'Edit Profile', edit_user_path(current_user), class:"btn btn-sm btn-default" %> 
    <% end %>
  </h1>
 
 <h4>Contact Information: <%= @user.email %></h4>

  <div class="col-md-5 col-xs-5" style="padding-top:10px">
    <h4><u>Current Classes</u></h4>
    <% @lectures.each do |lecture| %>
    <ul>
      <li><%= lecture.name %></li>
    </ul>
    <% end %>
  </div>
  
  <div class="col-md-5 col-xs-5" style="padding-top:10px">
    <h4><u>Posts</u></h4>
      <% @posts.each do |post| %>
      <ul style="list-style-type:none">
        <li><%= link_to post.title, post, class:"postlinks" %></li>
      </ul>
      <% end %>
  </div>

 
</div>

app/views/users/update.html.erb
hi